ALTER TABLE metrics
    ALTER COLUMN timestamp TYPE TIMESTAMP WITH TIME ZONE
    USING timestamp AT TIME ZONE 'UTC';

ALTER TABLE metrics
    ALTER COLUMN timestamp SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE metrics ADD COLUMN IF NOT EXISTS timestamp_local TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE metrics ADD COLUMN IF NOT EXISTS local_utc_offset_minutes INTEGER;
